# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

#google-ID: 'UA-112060364-2'

menu:
- {name: 'about us', folder: 'pages', file: 'about.html'}
- {name: 'booklist', folder: 'pages', file: 'books.html'}
- {name: 'contact us!', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/speculationUIUC'}
 - {icon: 'facebook', link: 'https://www.facebook.com/groups/speculation.uiuc/'}
- {icon: 'instagram', link: 'https://instagram.com/speculation.uiuc'}
- {icon: 'envelope', link: 'mailto:speculation.uiuc@gmail.com'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
